### ISSUE TITLE
error cannot find module angularfire2/auth  below is my profile.ts code

### ISSUE THREAD

**Issue by Asvi2304** [Asvi2304/ho#1]
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { AngularFireAuth } from "angularfire2/auth";
import { AngularFireDatabase } from "angularfire2/database";

import { Profile } from '../../model/profile';
import { SchedulePage } from '../pages/schedule/schedule';

@IonicPage()
@Component({
  selector: 'page-profile',
  templateUrl: 'profile.html',
})
export class ProfilePage {

    profile = {} as Profile;

  constructor(
      public navCtrl: NavController, 
      public navParams: NavParams, 
      private afAuth: AngularFireAuth, 
      private afDatabase: AngularFireDatabase) {
  }

  

  createProfile() {
      this.afAuth.authState.take(1).subscribe(auth => {
        //   const afList = this.afDatabase.list(`${auth.uid}`);
        //   afList.push(this.profile);
        //   const listObservable = afList.snapshotChanges();
        //   listObservable.subscribe(() => this.navCtrl.setRoot(HomePage));
        this.afDatabase.object(`profile/${auth.uid}`).set(this.profile)
            .then(() => this.navCtrl.setRoot(HomePage))

      })
  }

  
}

**Comment by Asvi2304** [comment]
any one here to help mee???

**Comment by Asvi2304** [comment]
rror: Unexpected value 'undefined' declared by the module 'AppModule'
    at syntaxError (http://localhost:8100/build/vendor.js:77796:34)
    at http://localhost:8100/build/vendor.js:92450:40
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:92448:54)
    at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:110814:87)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:110775:36)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:110691:37)
    at CompilerImpl.compileModuleAsync (http://localhost:8100/build/vendor.js:76632:49)
    at PlatformRef.bootstrapModule (http://localhost:8100/build/vendor.js:5796:25)
    at Object.214 (http://localhost:8100/build/main.js:950:109)
